baseURL = "https://techblog.shashura1.top/"
languageCode = "zh-cn"
title = "Shura 极客技术笔记"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  mathjax = true
  ShowToc = true
  TocOpen = false

  [params.profileMode]
    enabled = false

[taxonomies]
  category = "categories"

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "归档"
url = "/archives/"
weight = 2


