baseURL = "https://shura-techblog.pages.dev/"
languageCode = "zh-cn"
title = "Shura 极客技术笔记"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  mathjax = true
  ShowToc = true
  TocOpen = false

[[menu.main]]
name = "NAS折腾"
url = "/nas/"
weight = 1

[[menu.main]]
name = "AI本地部署"
url = "/ai/"
weight = 2

[[menu.main]]
name = "脚本&工具教程"
url = "/script/"
weight = 3

[[menu.main]]
name = "芯片硬件科普"
url = "/hardware/"
weight = 4

[[menu.main]]
name = "踩坑记录"
url = "/log/"
weight = 5

[params.twikoo]
enable = false
envId = ""
lang = "zh-CN"
